### ISSUE TITLE
Migrate to Python 3.7

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_server#94]
## Goal

Update the server code to Python 3 as the support for Python 2 will end with 2020 (see [countdown](https://pythonclock.org/)). Moreover, our customers urged to use Python 3 then, due to security issues.

## Resources

* [Official porting guide](https://docs.python.org/3/howto/pyporting.html)
* [Python 2 to 3 converter](https://www.pythonconverter.com/)
* If necessary: [Python \_\_future__ package](https://pypi.org/project/future/) "allows you to use a single, clean Python 3.x-compatible codebase to support both Python 2 and Python 3 with minimal overhead."

## Current status

* phovea_server uses already the [Python future library](https://github.com/phovea/phovea_server/blob/master/requirements.txt#L12) 
* https://github.com/phovea/phovea_server/tree/update_dependencies

## ⚠ Heads up!

* We must update also Python code of repos that are using the phovea_server as dependency
* We need to inform our customers and JKU about this update

## To discuss

* How to test that everything is working after the update?

## To-Do's

Things that should be done after updating all repositories:

- [ ] Deprecate the Docker image `caleydo/phovea_python`, since we are using the official Docker image `python:3.7`
   - [ ] Archive the repository https://github.com/phovea/phovea_python
- [ ] Deprecate the Docker image `caleydo/phovea_circleci_python`, since we are using the official CircleCI Docker image `python:3.7-node-browsers`
   - [ ] Archive the repository https://github.com/phovea/phovea_circleci_python
